language: cpp

before_install:
 - sudo apt-get update
 - sudo apt-get install tcl-dev #cython python-numpy
 - if [[ $with_fftw = true ]]; then sudo apt-get install libfftw3-dev; fi
 - if [[ $with_mpi = with ]]; then sudo apt-get install libopenmpi-dev openmpi-bin; fi

env:
  - with_fftw=true with_mpi=true
  - with_fftw=false with_mpi=false

matrix:
  exclude:
    - compiler: clang
      env: with_fftw=true with_mpi=true

script: ./maintainer/travis/build.sh

compiler:
  - clang
  - gcc
